when:
  - event: push
    branch: testing

steps:
  - name: testing-build-and-push
    image: woodpeckerci/plugin-docker-buildx:5
    settings:
      repo: pulp.artesanosdigitalescom.com.mx/fastapi-bugsink/app
      registry: pulp.artesanosdigitalescom.com.mx
      dockerfile: Dockerfile
      tags:
        - testing-${CI_COMMIT_SHA}
        - testing
      username:
        from_secret: pulp_user
      password:
        from_secret: pulp_password

  - name: testing-inject-secrets-and-deploy
    image: python:3.12-alpine
    depends_on: [testing-build-and-push]
    environment:
      DOKPLOY_API_KEY:
        from_secret: dokploy_api_key
      INFISICAL_CLIENT_ID:
        from_secret: infisical_client_id
      INFISICAL_CLIENT_SECRET:
        from_secret: infisical_client_secret
      COMPOSE_ID: SD0CDzsv2o_x3gI8PfHTY
      INFISICAL_ENVIRONMENT: dev
    commands:
      - python3 ci/inject_secrets_and_deploy.py
